### ISSUE TITLE
Протестировть Latency на PyTorch, HuggingFace и Triton

### ISSUE THREAD

**Issue by TORTIKOV** [ForkMyLife-Clinic-2023/Magic#12]
- [x] PyTorch
- [ ] HuggingFace
- [x] Triton
- [x] Сообщить результаты тестов команде

**Comment by HanBinGer** [comment]
С торчем получился полный провал: попробовал пару раз сгенерить ответ на 1024 токена - в итоге на него требовалось около 60 секунд, при этом модель почему-то не генерировала eos токен. В чём проблема: в оболочке или в самой модели так и не выяснил.
