### ISSUE TITLE
Добавить выбор организации в боте

### ISSUE THREAD

**Issue by mohorka** [ForkMyLife-Clinic-2023/Magic#27]
**Текущее состояние**: нам необходима опция выбора клиентом организации, про которую клиент будет общаться с ботом, так как это уточняет поведение языковой модели. Сейчас такой функции у нас нет.

**Шаги выполнения**:

1. Разобраться как работает добавление кнопок выбора в тг-бота.
2. Добавить метод, который будет при нажатии кнопки выводить клиенту текст с кнопки.
3. Интегрировать этот метод с dummy-методом, чтоб после нажатия клиентом кнопки и вывода названия в консоль клиент мог написать запрос, а бот ответил ему в формате `название организации: текст запроса`
С вопросами обращаться к @mohorka 

**Dod**: в боте работает функционал с выбором организации, умеем пробрасывать выбранную организацию в текст запроса.

**Comment by TORTIKOV** [comment]
От меня добро. Ждем @mohorka и закрываем тачку
